"""Collation — the chat template and the completion-only loss mask.

Two defects in the old trainer live here. It joined `system\\n\\nuser\\n\\ncompletion`
by hand, so the student learned a format it is never served with; and it computed
loss over the prompt as well as the answer, so most of the gradient came from
reproducing a rubric that is supplied at inference anyway.

The tokenizer is stubbed rather than downloaded: these assertions are about the
masking and the parity contract, and they must hold in CI with no network.
"""

from __future__ import annotations

import json
import re
from typing import Any

import pytest

from lexi_research.teacher import render_grader_prompt
from lexi_research.teacher.schemas import SenseRef
from lexi_research.train.collate import (
    IGNORE_INDEX,
    CollationError,
    SequenceTooLong,
    build_example,
    completion_text,
    training_messages,
)

ROW = {
    "target": "bright",
    "definition": "full of light; shining strongly",
    "pos": "adjective",
    "text": "The room is very bright today.",
    "correction": "The room is very bright today.",
    "meaning": 4,
    "feedback": "Natural sentence with the correct meaning.",
}

#: A special token is its own token even when glued to a word, so the boundary
#: between the completion and the turn terminator is unambiguous.
_TOKEN_RE = re.compile(r"<\|[^|]*\|>|\S+")


class StubTokenizer:
    """A deterministic chat tokenizer: no vocabulary file, no download.

    Renders a Qwen-shaped conversation and tokenises on whitespace, treating
    `<|...|>` as atomic. `enable_thinking` opens a reasoning block on the
    assistant turn, which is what the flag has to be able to change.

    `chat_template` carries a generation block only on the masking subclass,
    because that string is what production inspects to decide which path it can
    use — the same way `transformers` decides.
    """

    chat_template = "{% for message in messages %}…{% endfor %}"
    eos_token = "<|im_end|>"

    def __init__(self) -> None:
        self.vocab: dict[str, int] = {}

    def _assistant_header(self, enable_thinking: bool) -> str:
        header = "<|im_start|>assistant\n"
        return header + "<think>\n" if enable_thinking else header

    def render(
        self,
        messages: list[dict[str, str]],
        *,
        add_generation_prompt: bool = False,
        enable_thinking: bool = True,
    ) -> str:
        parts: list[str] = []
        for message in messages:
            if message["role"] == "assistant":
                parts.append(self._assistant_header(enable_thinking))
                parts.append(f"{message['content']}<|im_end|>\n")
            else:
                parts.append(f"<|im_start|>{message['role']}\n{message['content']}<|im_end|>\n")
        if add_generation_prompt:
            parts.append(self._assistant_header(enable_thinking))
        return "".join(parts)

    def _encode(self, text: str) -> list[int]:
        ids: list[int] = []
        for token in _TOKEN_RE.findall(text):
            ids.append(self.vocab.setdefault(token, len(self.vocab)))
        return ids

    def encode(self, text: str, **_: Any) -> list[int]:
        return self._encode(text)

    def decode(self, ids: list[int]) -> str:
        lookup = {index: token for token, index in self.vocab.items()}
        return " ".join(lookup[index] for index in ids)

    def apply_chat_template(
        self,
        messages: list[dict[str, str]],
        *,
        tokenize: bool = True,
        add_generation_prompt: bool = False,
        return_dict: bool = False,
        return_assistant_tokens_mask: bool = False,
        enable_thinking: bool = True,
        **_: Any,
    ) -> Any:
        text = self.render(
            messages,
            add_generation_prompt=add_generation_prompt,
            enable_thinking=enable_thinking,
        )
        if not tokenize:
            return text
        ids = self._encode(text)
        if not return_dict:
            return ids
        payload: dict[str, Any] = {"input_ids": ids, "attention_mask": [1] * len(ids)}
        if return_assistant_tokens_mask:
            # A template with no generation block returns a mask of zeros and a
            # warning, exactly as `transformers` does. It does not raise.
            payload["assistant_masks"] = (
                self._assistant_mask(messages, enable_thinking)
                if "generation" in self.chat_template
                else [0] * len(ids)
            )
        return payload

    def _assistant_mask(self, messages: list[dict[str, str]], enable_thinking: bool) -> list[int]:
        """1 for every token generated by the assistant, as a real template marks it."""
        mask: list[int] = []
        for message in messages:
            rendered = self.render([message], enable_thinking=enable_thinking)
            count = len(_TOKEN_RE.findall(rendered))
            if message["role"] != "assistant":
                mask += [0] * count
                continue
            header = len(_TOKEN_RE.findall(self._assistant_header(enable_thinking)))
            mask += [0] * header + [1] * (count - header)
        return mask


class MaskingStubTokenizer(StubTokenizer):
    chat_template = "{% for message in messages %}{% generation %}…{% endgeneration %}{% endfor %}"


@pytest.fixture(params=[StubTokenizer, MaskingStubTokenizer])
def tokenizer(request) -> StubTokenizer:
    """Both label paths: the template's assistant mask, and the concatenation."""
    return request.param()


def test_labels_mask_prompt(tokenizer) -> None:
    example = build_example(tokenizer, ROW, nonce="feedface")

    unmasked = [
        token
        for token, label in zip(example.input_ids, example.labels, strict=True)
        if label != IGNORE_INDEX
    ]
    boundary = len(example.labels) - len(unmasked)
    assert unmasked, "no completion tokens were supervised"
    assert all(label == IGNORE_INDEX for label in example.labels[:boundary])
    assert example.labels[boundary:] == example.input_ids[boundary:]

    expected = _TOKEN_RE.findall(completion_text(ROW) + "<|im_end|>")
    assert tokenizer.decode(unmasked) == " ".join(expected)


def test_chat_template_parity(tokenizer) -> None:
    """The prompt half must be what `serve/backend.py` sends, message for message."""
    served = render_grader_prompt(
        ROW["target"],
        SenseRef(definition=ROW["definition"], pos=ROW["pos"]),
        ROW["text"],
        nonce="feedface",
    )
    assert training_messages(ROW, nonce="feedface") == served

    example = build_example(tokenizer, ROW, nonce="feedface")
    prompt_ids = tokenizer.apply_chat_template(served, add_generation_prompt=True)
    assert list(example.input_ids[: len(prompt_ids)]) == prompt_ids
    assert all(label == IGNORE_INDEX for label in example.labels[: len(prompt_ids)])


def test_thinking_flag_changes_render(tokenizer) -> None:
    thinking = build_example(tokenizer, ROW, nonce="feedface", enable_thinking=True)
    plain = build_example(tokenizer, ROW, nonce="feedface", enable_thinking=False)

    assert thinking.input_ids != plain.input_ids
    assert "<think>" in tokenizer.decode(list(thinking.input_ids))
    assert "<think>" not in tokenizer.decode(list(plain.input_ids))


def test_full_sequence_mask_supervises_everything(tokenizer) -> None:
    """Ablation A7's other arm — the old trainer's behaviour, now selectable."""
    example = build_example(tokenizer, ROW, nonce="feedface", completion_only=False)
    assert list(example.labels) == list(example.input_ids)


def test_completion_is_sorted_json_of_the_three_answer_fields() -> None:
    payload = json.loads(completion_text(ROW))
    assert set(payload) == {"correction", "meaning", "feedback"}
    assert payload["meaning"] == 4


def test_null_correction_survives_the_round_trip() -> None:
    row = dict(ROW, correction=None)
    assert json.loads(completion_text(row))["correction"] is None


def test_an_example_over_the_limit_raises(tokenizer) -> None:
    """Truncation is not offered: cutting the tail teaches unterminated JSON,
    cutting the head drops the rubric the answer depends on. The caller drops
    the row and counts it."""
    with pytest.raises(SequenceTooLong):
        build_example(tokenizer, ROW, nonce="feedface", max_seq_len=4)


def test_an_example_within_the_limit_is_untouched(tokenizer) -> None:
    unlimited = build_example(tokenizer, ROW, nonce="feedface")
    limited = build_example(tokenizer, ROW, nonce="feedface", max_seq_len=len(unlimited.input_ids))
    assert limited.input_ids == unlimited.input_ids
    assert limited.labels == unlimited.labels


def test_attention_mask_covers_every_token(tokenizer) -> None:
    example = build_example(tokenizer, ROW, nonce="feedface")
    assert example.attention_mask == [1] * len(example.input_ids)


def test_a_misplaced_generation_block_raises() -> None:
    """A template that declares a generation block and marks nothing is broken.

    Distinct from a template with no block at all, which is the ordinary case and
    must fall back silently. Confusing the two is what made an earlier version of
    this module raise on every real checkpoint.
    """

    class BlindTokenizer(MaskingStubTokenizer):
        def _assistant_mask(self, messages, enable_thinking):  # type: ignore[no-untyped-def]
            return [0] * len(super()._assistant_mask(messages, enable_thinking))

    with pytest.raises(CollationError, match="generation block"):
        build_example(BlindTokenizer(), ROW, nonce="feedface")


def test_a_template_with_no_generation_block_falls_back() -> None:
    """`transformers` returns a zero mask and a warning rather than raising."""
    plain = StubTokenizer()
    assert "generation" not in plain.chat_template

    example = build_example(plain, ROW, nonce="feedface")
    assert example.supervised_tokens
    assert example.supervised_tokens < len(example.labels)


def test_an_asymmetric_template_still_masks_correctly() -> None:
    """Qwen inserts an empty reasoning block into the generation prompt only.

    Comparing a prompt render against a full-conversation render would break on
    exactly this, taking ablation A2's no-thinking arm with it.
    """

    class AsymmetricTokenizer(StubTokenizer):
        def render(self, messages, *, add_generation_prompt=False, enable_thinking=True):  # type: ignore[no-untyped-def]
            text = super().render(
                messages,
                add_generation_prompt=add_generation_prompt,
                enable_thinking=enable_thinking,
            )
            if add_generation_prompt and not enable_thinking:
                text += "<think> </think> "
            return text

    example = build_example(AsymmetricTokenizer(), ROW, nonce="feedface", enable_thinking=False)
    assert example.supervised_tokens
    assert example.supervised_tokens < len(example.labels)


def test_a_tokenizer_without_an_eos_token_raises() -> None:
    """The answer has to be terminated, or generation never stops."""

    class UnterminatedTokenizer(StubTokenizer):
        eos_token = ""

    with pytest.raises(CollationError, match="eos_token"):
        build_example(UnterminatedTokenizer(), ROW, nonce="feedface")


def test_the_fallback_holds_against_a_real_tokenizer() -> None:
    """The stub models an API; this proves the API is what the stub says it is.

    Published templates — Qwen, Llama, Mistral, Gemma — carry no generation block,
    so this is the path production actually takes.
    """
    pytest.importorskip("transformers")
    from lexi_research.cli.smoke import CHAT_TEMPLATE, build_tiny_tokenizer

    real = build_tiny_tokenizer([ROW], model_max_length=100_000)
    real.chat_template = re.sub(r"\{%\s*(end)?generation\s*%\}", "", CHAT_TEMPLATE)

    example = build_example(real, ROW, nonce="feedface")
    supervised = [
        token
        for token, label in zip(example.input_ids, example.labels, strict=True)
        if label != IGNORE_INDEX
    ]
    assert supervised
    assert supervised == real.encode(
        completion_text(ROW) + real.eos_token, add_special_tokens=False
    )


def test_the_template_path_holds_against_a_real_tokenizer() -> None:
    """The other arm: a template that does carry a generation block."""
    pytest.importorskip("transformers")
    from lexi_research.cli.smoke import build_tiny_tokenizer

    real = build_tiny_tokenizer([ROW], model_max_length=100_000)
    example = build_example(real, ROW, nonce="feedface")
    assert example.supervised_tokens
    assert example.supervised_tokens < len(example.labels)
